#page title
page_title                                : programR - Learn Apps Development From Scratch

# App Info
ios_app_id                                :
apk_link                                  : https://deive.google.com
appstore_link                             :
playstore_link                            : https://drive.google.com/download.apk                            # Enter Google Play Store URL.
presskit_download_link                    :                                       # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/app_icon.png
app_name                                  :  programR                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :  FREE                                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Want to create apps? We are here to teach you to create apps with smartphone. We have a online community too for helping each other and learn together.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Unknown                             
your_link                                 :              
your_city                                 : Earth                                
email_address                             :
facebook_username                         : programr.android                                        
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

 

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage (1).jpg                  # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : white                         # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"

sass:
  style: :compressed # You might prefer to minify using :compressed


exclude:
  - LICENSE
  - README.md
  - CNAME
  - SECURITY.md

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
